### PR TITLE
fix: unify user navigation touchpad and mouse interaction focus

### LINKED ISSUE #82: 在使用触摸板情况下，消息与个人导航窗口无法打开
如视频所示，只能通过三指以新标签页打开
版本 2.18.15

https://github.com/user-attachments/assets/3ef065c3-3101-4230-876e-e0b82798a5a6

### PR DESCRIPTION
**Pull request by youyou-sudo**
## Involved Issue / 该 PR 相关 Issue

Close #82 

## Note / 说明

在 `@mousedown` 和 `@touchstart` 事件处理器中手动调用 `focus()` 方法，以统一触摸板与鼠标交互

### CODE REVIEW

File: components/kun/top-bar/UserInfo.vue [hunk 1]
```diff
@@ -25,6 +25,10 @@ const handlePanelBlur = async () => {
   emits('close')
 }
 
+const handleMouseDown = (event: MouseEvent | TouchEvent) => {
```
Comment (youyou-sudo) [inline components/kun/top-bar/UserInfo.vue:28]: const handleMouseDown = (event: MouseEvent) => {

File: components/kun/top-bar/UserInfo.vue [hunk 2]
```diff
@@ -76,7 +80,14 @@ onMounted(async () => {
...
 
 <template>
-  <div ref="container" tabindex="-1" class="container" @blur="handlePanelBlur">
+  <div
+    ref="container"
+    tabindex="-1"
+    class="container"
+    @blur="handlePanelBlur"
+    @mousedown.prevent="handleMouseDown"
+    @touchstart.prevent="handleMouseDown"
```
Comment (youyou-sudo) [inline components/kun/top-bar/UserInfo.vue:89]: <div
    ref="container"
    tabindex="-1"
    class="container"
    @blur="handlePanelBlur"
    @mousedown.prevent="handleMouseDown"
  >
